version: '3.8'

services:

  jupyter:
    build: ./jupyter
    restart: unless-stopped
    ports:
      - "8200:8888"
    entrypoint:
      jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    volumes: 
      - ./jupyter:/app
    env_file: 
      - ./jupyter/variables.env

  postgresql:
    image: "postgres:14"
    restart: unless-stopped
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: itguymichal
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin4:latest"
    restart: unless-stopped
    ports: 
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: p4ssw0rd
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
volumes:
  db-data:
  pgadmin-data:
  
  
